// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/go-kit/log"
	"github.com/shivamk2406/newsletter-subscriptions/internal/config"
	"github.com/shivamk2406/newsletter-subscriptions/internal/service"
	"github.com/shivamk2406/newsletter-subscriptions/internal/service/news"
	"github.com/shivamk2406/newsletter-subscriptions/internal/service/subscriptions"
	"github.com/shivamk2406/newsletter-subscriptions/internal/service/users"
	"github.com/shivamk2406/newsletter-subscriptions/pkg/database"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeConfig() (config.Config, error) {
	configConfig, err := config.LoadDatabaseConfig()
	if err != nil {
		return config.Config{}, err
	}
	return configConfig, nil
}

func initializeDB(conf config.Config) (*gorm.DB, func(), error) {
	db, cleanup, err := database.Open(conf)
	if err != nil {
		return nil, nil, err
	}
	return db, func() {
		cleanup()
	}, nil
}

func initializeRegistry(db *gorm.DB, log2 log.Logger) *service.Registry {
	subscriptionDB := subscriptions.NewSubscriptionRepo(db)
	subscriptionManagement := subscriptions.NewSubscriptionService(subscriptionDB, log2)
	newsDB := news.NewNewsRepo(db)
	newsManagement := news.NewsManagementService(newsDB, log2)
	usersDB := users.NewUsersRepo(db)
	userManagement := users.UserManagementService(usersDB, log2)
	registry := service.ServiceRegistry(subscriptionManagement, newsManagement, userManagement)
	return registry
}
