// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/shivamk2406/item-inventory/internal/config"
	"github.com/shivamk2406/item-inventory/internal/service/item"
	"github.com/shivamk2406/item-inventory/pkg/database"
)

// Injectors from wire.go:

func InitializeFactory() (*item.Repository, error) {
	configConfig, err := config.InitializeConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.InitializeDB(configConfig)
	if err != nil {
		return nil, err
	}
	repository, err := item.InitializeRepo(db)
	if err != nil {
		return nil, err
	}
	return repository, nil
}
