// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/shivamk2406/item-inventory/internal/service"
	"github.com/shivamk2406/item-inventory/internal/service/item"
)

// Injectors from wire.go:

func Wire() *item.Repository {
	config := service.ProviderConfig()
	db := service.ProviderDB(config)
	repository := service.ProviderRepo(db)
	return repository
}

// wire.go:

var (
	ProviderSet wire.ProviderSet = wire.NewSet(service.ProviderConfig, service.ProviderDB, service.ProviderRepo)
)
