// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/shivamk2406/item-inventory/internal/config"
	"github.com/shivamk2406/item-inventory/internal/service"
	"github.com/shivamk2406/item-inventory/internal/service/item"
)

// Injectors from wire.go:

func Wire(conf config.Config) *item.Repository {
	db := service.ProviderDB(conf)
	repository := item.ProviderRepo(db)
	return repository
}

// wire.go:

var (
	ProviderSet wire.ProviderSet = wire.NewSet(service.ProviderDB, item.ProviderRepo)
)
