database:
  user: alpha
  password: alpha
  host: 127.0.0.1:3306
  name: newslet
  maxIdleConnections: 5
  maxOpenConnections: 5
  maxConnectionLifetime: 150s
  maxConnectionIdletime: 150s
  disableTLS: true