// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/shivamk2406/item-inventory/internal/service (interfaces: DB)

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	item "github.com/shivamk2406/item-inventory/domain/item"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// GetInventoryItem mocks base method.
func (m *MockDB) GetInventoryItem() ([]item.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventoryItem")
	ret0, _ := ret[0].([]item.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventoryItem indicates an expected call of GetInventoryItem.
func (mr *MockDBMockRecorder) GetInventoryItem() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventoryItem", reflect.TypeOf((*MockDB)(nil).GetInventoryItem))
}
